cc_binary(
    name = "submit-1",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SUBMIT_ALL",
        "TARGET_DIR=/c/cs323/proj1/.submit",
        "GET_DIR_PREFIX=/home/accts",
    ],
)

cc_binary(
    name = "submit-2",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SUBMIT_SINGLE=dmalloc.cc",
        "TARGET_DIR=/c/cs323/proj2/.submit",
        "GET_DIR_PREFIX=/home/accts",
    ],
)

cc_binary(
    name = "submit-4",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SUBMIT_SINGLE=process.c",
        "TARGET_DIR=/c/cs323/proj4/.submit",
        "GET_DIR_PREFIX=/home/accts",
    ],
)

cc_binary(
    name = "submit-5",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SUBMIT_LIST=STR(kernel.c),STR(kernel.h),STR(k-loader.c)",
        "TARGET_DIR=/c/cs323/proj4/.submit",
        "GET_DIR_PREFIX=/home/accts",
    ],
)

cc_binary(
    name = "submit-final",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SUBMIT_LIST=STR(kernel.c),STR(kernel.h),STR(k-loader.c),STR(malloc.c)",
        "TARGET_DIR=/c/cs323/final-proj/.submit",
        "GET_DIR_PREFIX=/home/accts",
    ],
)
