cc_binary(
    name = "submit-1",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "ALL",
        "HWK=1"
    ],
)

cc_binary(
    name = "submit-2",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SINGLE=dmalloc.cc",
        "HWK=2"
    ],
)

cc_binary(
    name = "submit-4",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "ALL",
        "HWK=4"
    ],
)
